shared:
  image: runmymind/docker-android-sdk

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - export: echo 'Hello, building now!'
      - run_arbitrary_script: ./gradlew assembleRelease
      - cleanup: echo 'All done, bye!'
