shared:
    image: node:6

jobs:
    template:
        requires: [~pr, ~commit]
        steps:
            - prep: npm install screwdriver-template-main
            - template: node ./node_modules/.bin/template-publish
        environment:
              SD_TEMPLATE_PATH: './sd-template-publish.yaml'
    android:
        requires: [template]
        template: screwdriver/template-publish
        steps:
            - preinstall: echo 'Publishing Android template.'
            - postpublish: echo 'Template published.'
        environment:
              SD_TEMPLATE_PATH: './sd-template-android.yaml'

