shared:
    image: node:6

jobs:
    builder:
        requires: [~pr, ~commit]
        template: screwdriver/android-build
        steps:
            - preprebuild: echo 'Attempting to retrieve template.
            - postpostbuild: echo 'Job's done.
        environment:
              SD_TEMPLATE_PATH: './sd-template-publish.yaml'
