shared:
  image: buildpack-deps

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - export: echo 'Hello, building now!'
      - run_arbitrary_script: ./gradlew assembleRelease
      - cleanup: echo 'All done, bye!'
