shared:
  image: node:6

jobs:
  template:
    requires: [~pr, ~commit]
    steps:
      - prep: npm install screwdriver-template-main
      - movefile: mv sd-template-publish.yaml sd-template.yaml
      - publish: node ./node_modules.bin/template-publish
      - cleanup: echo 'Template loaded.'
  build:
    requires: [template]
    template: screwdriver/template-publish
    steps:
       - prebuild: mv sd-template-android.yaml sd-template.yaml
       - postbuild: echo 'Job's done.'
