jobs:
    builder:
        requires: [~pr, ~commit]
        template: screwdriver/android-build
        steps:
            - preprebuild: echo 'Attempting to retrieve template.
            - postpostbuild: echo 'Job's done.
