jobs:
    builder:
        requires: [~pr, ~commit]
        template: screwdriver/android-build
        steps:
            - preprebuild: echo 'Attempting to retrieve template.'
            - postpostbuild: echo 'Job\'s done.'
            - save: mv ./app/builds/outputs/apk/release/app-release-unsigned.apk $SD_ARTIFACT_DIR/release.apk
