shared:
    image: node:6

jobs:
    pub:
        requires: [~pr, ~commit]
        steps:
            - prep: npm install screwdriver-template-main
            - template: node ./node_modules/.bin/template-publish
        environment:
              SD_TEMPLATE_PATH: './sd-template-publish.yaml'
              SD_API_URL: 'http://192.168.0.34:9001/v4/'
    android:
        requires: [pub]
        template: screwdriver/template-publish
        steps:
            - preinstall: echo 'Publishing Android template.'
            - postpublish: echo 'Template published.'
        environment:
              SD_TEMPLATE_PATH: './sd-template-android.yaml'
              SD_API_URL: 'http://192.168.0.34:9001/v4/'


